
#define	FORM_Create_Dire	    0

#define V_Dir_Name	    2
#define VDir_OK	    5
#define VDir_CANCEL	    6

#define	FORM_Create_PRog	    1

#define VProg_Name	    3
#define VProg_Path	    4
#define VProg_Path_FS	    7
#define VProg_OK	    8
#define VProg_CANCEL	    9
#define Argument_Box	   10
#define Argument_None	   12
#define Argument_Ask	   13
#define Argument_Below	   14
#define Arg_Line1	   15
#define Arg_Line3	   16
#define Arg_Line2	   17
#define Working_Dir_Box	   18
#define Working_Program	   20
#define Working_Below	   21
#define Working_Dir_Text	   22
#define Working_Dir_FS	   23

#define	FORM_Ask_For_Arg	    2

#define Ask_Prog_Name	    2
#define Ask_Args1	    5
#define Ask_Args2	    6
#define Ask_Args3	    7
#define Ask_Args_OK	    8
#define Ask_Args_CANCEL	    9

#define	Normal_Tos	    3

#define MNU_AVFM_Edit	    5
#define MNU_AVFM_About	    8
#define MNU_AVFM_Quit	   17
#define MNU_AVFM_Save	   18
#define MNU_AVFM_Other	   20
#define MNU_AVFM_Cut	   23
#define MNU_AVFM_Copy	   24
#define MNU_AVFM_Paste	   25
#define MNU_AVFM_Add_New	   27
#define MNU_AVFM_Edit_Hi	   28

#define	FORM_Create_Doc	    4

#define VD_Document_Name	    3
#define VD_Document_Path	    4
#define VD_FS	    7
#define VD_OK	    8
#define VD_CANCEL	    9
#define VD_Comment1	   12
#define VD_Comment2	   13
#define VD_Comment3	   14
#define VD_Package_Path	   17
#define VD_Package_FS	   18
#define VD_Package_List	   19
#define VD_Version_No	   24
#define VD_Date_Created	   25
#define VD_Date_Edited	   26

#define	FORM_Create_What	    5

#define Create_CANCEL	    2
#define Create_OK	    3
#define Create_What_Box	    4
#define Create_DOC	    5
#define Create_PROG	    6
#define Create_DIR	    7

#define	About_AVFM	    6

#define About_Ver_Text	    6
#define About_Ver_Date	    7

#define	FORM8	    7

